### ISSUE TITLE
TypeError when a user exception is thrown

### ISSUE THREAD

**Issue by 71104** [71104/lambda#50]
Run on bash:

```bash
$ echo "throw 0" | lambda
```

Output:

```
net.js:633
    throw new TypeError('invalid data');
          ^
TypeError: invalid data
    at WriteStream.Socket.write (net.js:633:11)
    at Socket.<anonymous> (/usr/lib/node_modules/lambda/bin/Main.js:32:19)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

The expected output is a string representation of the thrown exception.

**Comment by 71104** [comment]
It works regularly when run in TTY mode.
