### ISSUE TITLE
Bug in native object extension

### ISSUE THREAD

**Issue by 71104** [71104/lambda#85]
Likely caused by the fix for #75.

```
> let Math.lol = Math.pow in Math.lol 1 2
TypeError: left.context.top(...).bindThis is not a function
    at AbstractNode.FieldAccessNode.evaluate (lambda/bin/lambda.js:1139:59)
    at AbstractNode.ApplicationNode.evaluate (lambda/bin/lambda.js:1262:24)
    at AbstractNode.ApplicationNode.evaluate (lambda/bin/lambda.js:1262:24)
    at AbstractNode.LetNode.evaluate (lambda/bin/lambda.js:1311:20)
    at lambda/bin/Main.js:23:49
    at REPLServer.require.start.eval (lambda/bin/Main.js:32:18)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:77:13)
```

**Comment by 71104** [comment]
After the fixes provided by 809b7b28225d3105fd84a2a790a1e8d096a2f2f4 this still fails with a runtime error:

```
> let Math.lol = Math.pow in Math.lol 2 3
runtime error
```

This time the root cause is that `Closure.marshal` doesn't keep the `length` of the function because it returns a wrapper function whose `length` is always 0. Therefore, when the closure is unmarshalled back, it defaults to length `1` and produces a function that receives only 1 argument.

In fact, this "works":

```
> let Math.lol = Math.pow in Math.lol 2
0
```
